version: "3.3"

services:
  # Database
  db:
    image: mariadb
    container_name: wp_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "18766:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wp_dev_site
      MYSQL_USER: wp_dev
      MYSQL_PASSWORD: wpdevdb_password
    restart: unless-stopped
    networks:
      - net
  # Wordpress
  wp:
    depends_on:
      - db
    image: wordpress:php8.3
    container_name: wp_instance
    user: 0:0
    volumes:
      - ./app:/var/www/html/wp-content/:rw
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    ports:
      - "18765:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_dev_site
      WORDPRESS_DB_USER: wp_dev
      WORDPRESS_DB_PASSWORD: wpdevdb_password
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
    restart: always
    networks:
      - net
  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: wp_phpmyadmin
    ports:
      - "18767:80"
    environment:
      PMA_HOST: db
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - db
  # WP-CLI
  wpcli:
    image: wordpress:cli-php8.3
    links:
      - db:db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_dev_site
      WORDPRESS_DB_USER: wp_dev
      WORDPRESS_DB_PASSWORD: wpdevdb_password
    volumes_from:
      - wp
    depends_on:
      - db
      - wp
    networks:
      - net
networks:
  net:
volumes:
  www_data:
  db_data:
